import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        {children}
        <Toaster
          position="bottom-right"
          toastOptions={{
            style: {
              background: "#1A3C34",
              color: "#F4F1EA",
              border: "1px solid rgba(212, 185, 150, 0.2)",
              borderRadius: "0px",
              fontFamily: "serif",
              padding: "1.5rem",
            },
            classNames: {
              toast: "bg-[#1A3C34] border border-[#D4B996]/20 rounded-none",
              title: "text-[#F4F1EA] font-serif italic text-lg",
              // Adding ! (important) to force the color override
              description:
                "!text-[#F4F1EA]/80 font-light tracking-widest text-[10px] uppercase mt-2 leading-relaxed",
              success: "bg-[#1A3C34] text-[#F4F1EA]", // Ensures success state doesn't change colors
            },
          }}
        />
      </body>
    </html>
  );
}
